// <auto-generated>
// Generated by scripts/Generate-ApiSpecCatalog.ps1 from
// SharpProof.Specs/RelationalSpecPackCatalog.json.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.Specs;

internal sealed record RelationalSpecPackCatalog(
    ImmutableDictionary<string, RelationalSpecPack> Packs,
    int Version, string EvidenceSha256);

internal sealed record RelationalSpecPack(
    string Id, string Version,
    ImmutableArray<RelationalSpecPackMethod> Methods);

internal sealed record RelationalSpecPackMethod(
    string DocumentationCommentId,
    ImmutableArray<ApiSpecAssemblyIdentity> Assemblies,
    ImmutableArray<IrTypeKind> ParameterTypes,
    IrTypeKind ResultType, SpecTermDeclaration Result,
    string EvidenceSha256 = "", string EvidenceIdentity = "");

internal static class RelationalSpecPackCatalogData
{
    internal static RelationalSpecPackCatalog Catalog { get; } = Create();

    private static RelationalSpecPackCatalog Create()
    {
        var packs = ImmutableDictionary.CreateBuilder<string, RelationalSpecPack>(
            StringComparer.Ordinal);
        packs.Add(
            "dotnet.scalar",
            new RelationalSpecPack(
                "dotnet.scalar",
                "1",
                [
                    new RelationalSpecPackMethod(
                        "M:System.Math.Max(System.Int32,System.Int32)",
                        [new ApiSpecAssemblyIdentity("System.Private.CoreLib", "7cec85d7bea7798e"), new ApiSpecAssemblyIdentity("System.Runtime", "b03f5f7f11d50a3a"), new ApiSpecAssemblyIdentity("mscorlib", "b77a5c561934e089")],
                        [IrTypeKind.Integer, IrTypeKind.Integer],
                        IrTypeKind.Integer,
                        new SpecConditionalDeclaration(new SpecBinaryDeclaration(IrBinaryOperator.GreaterThanOrEqual, new SpecVariableDeclaration(SpecVariableRole.Parameter, 0, IrTypeKind.Integer), new SpecVariableDeclaration(SpecVariableRole.Parameter, 1, IrTypeKind.Integer), IrTypeKind.Boolean), new SpecVariableDeclaration(SpecVariableRole.Parameter, 0, IrTypeKind.Integer), new SpecVariableDeclaration(SpecVariableRole.Parameter, 1, IrTypeKind.Integer), IrTypeKind.Integer)),
                ]));
        return new RelationalSpecPackCatalog(
            packs.ToImmutable(),
            1,
            "14d0e3b98982e7f19d90a90624caf95fa444f6131e7543518b3bfd7ff9198c22");
    }
}
