using NUnit.Framework;

namespace SharpProof.ArchitectureTest;

[TestFixture]
[NonParallelizable]
public sealed class DeclarativeModelGenerationTests
{
    [Test]
    public async Task OrphanedDeclarativeModelOutputIsRejected()
    {
        using var temporary = new TempDirectory("SharpProof.DeclarativeModels-");
        var root = temporary.FullName;
        var repository = TestRepository.FindRoot();
        foreach (var file in new[]
                 {
                     "global.json",
                     "scripts/Generate-DeclarativeModels.ps1",
                     "scripts/GeneratedFileHelpers.ps1",
                     "scripts/CSharpSourceMetrics.ps1",
                     "scripts/Assert-SharpProofJsonProperties.ps1"
                 })
        {
            CopyFile(repository, root, file);
        }

        await File.WriteAllTextAsync(
            Path.Combine(root, "SharpProof.DeclarativeModels.catalog.json"),
            """
            {
              "schema": "SharpProof.DeclarativeModels",
              "schemaVersion": 1,
              "outputs": [
                {
                  "path": "Generated/DeclarativeModels.generated.cs",
                  "namespace": "Fixture",
                  "classes": [],
                  "records": [],
                  "containers": []
                }
              ]
            }
            """);

        var script = Path.Combine(
            root,
            "scripts",
            "Generate-DeclarativeModels.ps1");
        var generated = await ArchitectureRepository.RunProcessAsync(
            root,
            "pwsh",
            "-NoLogo",
            "-NoProfile",
            "-File",
            script);
        Assert.That(generated.ExitCode, Is.Zero, generated.Error);

        var orphan = Path.Combine(
            root,
            "Orphan",
            "DeclarativeModels.generated.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(orphan)!);
        await File.WriteAllTextAsync(
            orphan,
            """
            // <auto-generated>
            // Generated by scripts/Generate-DeclarativeModels.ps1 from
            // SharpProof.DeclarativeModels.catalog.json.
            // Declarative record storage only; analysis remains handwritten.
            // Do not edit this file directly.
            // </auto-generated>
            #nullable enable
            namespace Orphan;
            """);

        var otherGeneratorFile = Path.Combine(
            root,
            "Other",
            "Other.generated.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(otherGeneratorFile)!);
        await File.WriteAllTextAsync(
            otherGeneratorFile,
            "// <auto-generated>\n// Generated by another generator.\n");

        var result = await ArchitectureRepository.RunProcessAsync(
            root,
            "pwsh",
            "-NoLogo",
            "-NoProfile",
            "-File",
            script,
            "-Verify");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.ExitCode, Is.Not.Zero);
            Assert.That(
                result.Error + result.Output,
                Does.Contain("Orphan/DeclarativeModels.generated.cs"));
        }

        File.Delete(orphan);
        var verified = await ArchitectureRepository.RunProcessAsync(
            root,
            "pwsh",
            "-NoLogo",
            "-NoProfile",
            "-File",
            script,
            "-Verify");
        Assert.That(verified.ExitCode, Is.Zero, verified.Error);
    }

    private static void CopyFile(string repository, string root, string relativePath)
    {
        var normalized = relativePath.Replace('/', Path.DirectorySeparatorChar);
        var source = Path.Combine(repository, normalized);
        var destination = Path.Combine(root, normalized);
        Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
        File.Copy(source, destination);
    }
}
