name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "3.1.x"

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build analyzer projects
        run: |
          dotnet build PurelySharp/PurelySharp.csproj --configuration Release --no-restore
          dotnet build PurelySharp.CodeFixes/PurelySharp.CodeFixes.csproj --configuration Release --no-restore
          dotnet build PurelySharp.Package/PurelySharp.Package.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test PurelySharp.Test/PurelySharp.Test.csproj --configuration Release --verbosity normal

      - name: Build VSIX project
        run: |
          dotnet build PurelySharp.Vsix/PurelySharp.Vsix.csproj --configuration Release /p:EnableVsixPackaging=true

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: PurelySharp.Vsix/bin/Release/*.vsix
          if-no-files-found: warn

      - name: Package NuGet
        run: dotnet pack PurelySharp.Package/PurelySharp.Package.csproj --configuration Release --output nupkgs

      - name: Upload NuGet artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: nupkgs/*.nupkg
